'use strict';

const fs = require('fs-extra');
const chalk = require('chalk');
const { readIndex } = require('../lib/index');
const { readEntry } = require('../lib/entries');
const { requireInit } = require('../lib/guard');

function exportLore() {
  requireInit();
  try {
    const index = readIndex();
    const allEntries = [];

    for (const entryPath of Object.values(index.entries)) {
      const entry = readEntry(entryPath);
      if (entry) allEntries.push(entry);
    }

    const byType = {
      decision: allEntries.filter(e => e.type === 'decision'),
      invariant: allEntries.filter(e => e.type === 'invariant'),
      graveyard: allEntries.filter(e => e.type === 'graveyard'),
      gotcha: allEntries.filter(e => e.type === 'gotcha'),
    };

    let md = '# Project Lore\n';
    md += '> Auto-generated by lore export. Do not edit manually — run `lore export` to regenerate.\n\n';

    if (byType.decision.length > 0) {
      md += '## Architectural Decisions\n';
      for (const e of byType.decision) {
        md += `- **${e.title}** (\`${e.files.join(', ')}\`): ${e.context}\n`;
        if (e.alternatives && e.alternatives.length > 0) {
          md += `  - Alternatives considered: ${e.alternatives.join('; ')}\n`;
        }
        if (e.tradeoffs) {
          md += `  - Tradeoffs: ${e.tradeoffs}\n`;
        }
      }
      md += '\n';
    }

    if (byType.invariant.length > 0) {
      md += '## Invariants\n';
      for (const e of byType.invariant) {
        md += `- **${e.title}** (\`${e.files.join(', ')}\`): ${e.context}\n`;
      }
      md += '\n';
    }

    if (byType.graveyard.length > 0) {
      md += '## Graveyard (Abandoned Approaches)\n';
      for (const e of byType.graveyard) {
        md += `- **${e.title}** (\`${e.files.join(', ')}\`): ${e.context}\n`;
      }
      md += '\n';
    }

    if (byType.gotcha.length > 0) {
      md += '## Gotchas\n';
      for (const e of byType.gotcha) {
        md += `- **${e.title}** (\`${e.files.join(', ')}\`): ${e.context}\n`;
      }
      md += '\n';
    }

    fs.writeFileSync('CLAUDE.md', md);
    console.log(chalk.green('✓ CLAUDE.md written to project root — Claude Code will read this on next session start'));
  } catch (e) {
    console.error(chalk.red(`Failed to export: ${e.message}`));
    process.exit(1);
  }
}

module.exports = exportLore;
