'use strict';

const fs = require('fs-extra');
const path = require('path');
const yaml = require('js-yaml');
const chalk = require('chalk');
const { LORE_DIR, emptyIndex } = require('../lib/index');

async function init() {
  try {
    const dirs = ['decisions', 'invariants', 'graveyard', 'gotchas', 'modules', 'sessions', 'drafts'];
    for (const dir of dirs) {
      await fs.ensureDir(path.join(LORE_DIR, dir));
    }

    const indexPath = path.join(LORE_DIR, 'index.json');
    if (!fs.existsSync(indexPath)) {
      await fs.writeJson(indexPath, emptyIndex(), { spaces: 2 });
    }

    const configPath = path.join(LORE_DIR, 'config.yaml');
    if (!fs.existsSync(configPath)) {
      const config = {
        version: '1.0',
        project: path.basename(process.cwd()),
        staleAfterDays: 30,
        embed: {
          model: 'nomic-embed-text',
          autoEmbed: true,
        },
        mcp: {
          tokenBudget: 4000,
          confirmEntries: true,
        },
        watchMode: false,
        watchIgnore: ['node_modules', 'dist', '.git', 'coverage'],
        commentPatterns: ["don't", 'never', 'always', 'because', 'warning', 'hack', 'note:', 'important:'],
        signalThreshold: 30,
        semanticStaleness: true,
        scoringWeights: { coverage: 0.4, freshness: 0.35, depth: 0.25 },
      };
      await fs.writeFile(configPath, yaml.dump(config));
    }

    // Create a .lore/.gitignore so generated/ephemeral files are excluded
    // but entry json files, config.yaml, and index.json are committed.
    const loreGitignorePath = path.join(LORE_DIR, '.gitignore');
    if (!fs.existsSync(loreGitignorePath)) {
      await fs.writeFile(loreGitignorePath,
        '# Auto-generated by lore init\nembeddings.db\nsessions/\nwatch-state.json\nwatcher.pid\nwatcher.log\nscore.json\n'
      );
    }

    console.log(chalk.green(`✓ Lore initialized at ${LORE_DIR}/`));
    console.log(chalk.cyan('  Run: lore mine .       to scan codebase for lore-worthy comments'));
    console.log(chalk.cyan('  Run: lore log          to create your first entry manually'));
    console.log(chalk.cyan('  Run: lore watch        to start passive capture'));
    console.log(chalk.cyan('  Run: lore serve        to start the MCP server'));

    // Auto-mine the codebase on first init if source files exist
    const index = require('../lib/index').readIndex();
    const entryCount = Object.keys(index.entries).length;
    if (entryCount === 0) {
      const { globSync } = require('glob');
      const hasSource = globSync('**/*.{js,ts,jsx,tsx}', {
        cwd: process.cwd(),
        ignore: ['node_modules/**', 'dist/**', '.lore/**'],
        absolute: false,
      }).length > 0;

      if (hasSource) {
        console.log(chalk.dim('\n  Scanning codebase for lore-worthy comments...'));
        try {
          const { mineDirectory } = require('../watcher/comments');
          const count = await mineDirectory(process.cwd(), process.cwd());
          if (count > 0) {
            console.log(chalk.cyan(`  Found ${count} draft entr${count === 1 ? 'y' : 'ies'} — run: lore drafts`));
          }
        } catch (e) {
          // Non-fatal
        }
      }
    }
  } catch (e) {
    console.error(chalk.red(`Failed to initialize Lore: ${e.message}`));
    process.exit(1);
  }
}

module.exports = init;
